#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_path="$( \
  export \                                                                                              _OLDPWD="$(pwd)" && \
    cd \
      "$(dirname \
           "${BASH_SOURCE[0]}")" && \
    echo \
      "$(pwd)" && \
    cd "${_OLDPWD}")" && \
    unset \
      _OLDPWD

app_name="$( \
  basename \
    "${BASH_SOURCE[0]}")"

# Add an user
_setup_user() {
  local \
    _user="${1}" \
    _home
  _home="/home/${_user}"
  useradd \
    "${_user}"
  mkdir \
    -p \
      "${_home}"
  chown \
    -R \
      "${_user}" \
      "${_home}"
  chmod \
    700 \
      "${_home}"
}

_msg_error() {
  local \
    _msg=(
      "$@")
  echo \
    "${_msg[*]}"
  exit
}

_usage() {
  echo \
    "Usage: ${app_name} <new_user>"
}

_user="${1}"

if (( $# < 1 )); then
  _usage
  _msg_error \
    "No user specified"
fi

_setup_user \
  "${_user}"

# vim:set sw=2 sts=-1 et:
